INSERT INTO cars (make_id, model, year, color) VALUES (1, Golf, 2007, red)
INSERT INTO cars (make_id, model, year, color) VALUES (3, Accord, 2000, red)
INSERT INTO cars (make_id, model, year, color) VALUES (5, Fabia, 2016, black)
INSERT INTO cars (make_id, model, year, color) VALUES (1, Golf, 2008, white)
INSERT INTO cars (make_id, model, year, color) VALUES (4, A4, 1999, green)
INSERT INTO cars (make_id, model, year, color) VALUES (2, Auris, 2011, blue)
INSERT INTO cars (make_id, model, year, color) VALUES (2, Prius, 2011, white)
INSERT INTO cars (make_id, model, year, color) VALUES (5, Fabia, 2016, black)
INSERT INTO cars (make_id, model, year, color) VALUES (1, Golf, 2008, white)
INSERT INTO cars (make_id, model, year, color) VALUES (4, A4, 1999, green)
INSERT INTO cars (make_id, model, year, color) VALUES (3, Civic, 2005, green)
INSERT INTO cars (make_id, model, year, color) VALUES (5, Superb, 2016, black)
INSERT INTO cars (make_id, model, year, color) VALUES (1, Up, 2017, black)
INSERT INTO cars (make_id, model, year, color) VALUES (4, A4 Quatro, 1996, grey)
INSERT INTO cars (make_id, model, year, color) VALUES (1, Golf, 2007, red)
INSERT INTO cars (make_id, model, year, color) VALUES (3, Accord, 2000, red)
INSERT INTO cars (make_id, model, year, color) VALUES (5, Fabia, 2016, black)
INSERT INTO cars (make_id, model, year, color) VALUES (1, Golf, 2008, white)
INSERT INTO cars (make_id, model, year, color) VALUES (4, A4, 1999, green)
INSERT INTO cars (make_id, model, year, color) VALUES (2, Auris, 2011, blue)
INSERT INTO cars (make_id, model, year, color) VALUES (2, Prius, 2011, white)
INSERT INTO cars (make_id, model, year, color) VALUES (5, Fabia, 2016, black)
INSERT INTO cars (make_id, model, year, color) VALUES (1, Golf, 2008, white)
INSERT INTO cars (make_id, model, year, color) VALUES (4, A4, 1999, green)
INSERT INTO cars (make_id, model, year, color) VALUES (5, Superb, 2016, black)
INSERT INTO cars (make_id, model, year, color) VALUES (1, Up, 2017, black)
INSERT INTO cars (make_id, model, year, color) VALUES (4, A4 Quatro, 1996, grey)
INSERT INTO cars (make_id, model, year, color) VALUES (1, Golf, 2007, red)
INSERT INTO cars (make_id, model, year, color) VALUES (3, Accord, 2000, red)
INSERT INTO cars (make_id, model, year, color) VALUES (1, Golf, 2008, orange)
INSERT INTO cars (make_id, model, year, color) VALUES (4, A4, 1999, green)
INSERT INTO cars (make_id, model, year, color) VALUES (2, Auris, 2011, blue)
INSERT INTO cars (make_id, model, year, color) VALUES (2, Corolla, 2011, gold)
INSERT INTO cars (make_id, model, year, color) VALUES (5, Fabia, 2016, blue)
INSERT INTO cars (make_id, model, year, color) VALUES (1, Polo, 2008, white)
INSERT INTO cars (make_id, model, year, color) VALUES (4, A4, 1999, green)
INSERT INTO cars (make_id, model, year, color) VALUES (3, Civic, 2005, black)
INSERT INTO cars (make_id, model, year, color) VALUES (5, Octavia, 2016, red)
INSERT INTO cars (make_id, model, year, color) VALUES (1, Up, 2017, black)
INSERT INTO cars (make_id, model, year, color) VALUES (4, A4 Quatro, 1996, red)
INSERT INTO cars (make_id, model, year, color) VALUES (5, Superb, 2016, black)
INSERT INTO cars (make_id, model, year, color) VALUES (1, Up, 2017, black)
INSERT INTO cars (make_id, model, year, color) VALUES (4, A4 Quatro, 2001, grey)
INSERT INTO cars (make_id, model, year, color) VALUES (1, Golf, 2007, red)
INSERT INTO cars (make_id, model, year, color) VALUES (5, Fabia, 2016, black)
INSERT INTO cars (make_id, model, year, color) VALUES (1, Golf, 1998, orange)
INSERT INTO cars (make_id, model, year, color) VALUES (4, A4, 1999, green)
INSERT INTO cars (make_id, model, year, color) VALUES (2, Auris, 2007, blue)
INSERT INTO cars (make_id, model, year, color) VALUES (8, Model S, 2015, red)
