INSERT INTO cars (make) VALUES (Volkswagen)
INSERT INTO cars (make) VALUES (Toyota)
INSERT INTO cars (make) VALUES (Honda)
INSERT INTO cars (make) VALUES (Audi)
INSERT INTO cars (make) VALUES (Skoda)
INSERT INTO cars (make) VALUES (Citroen)
INSERT INTO cars (make) VALUES (Opel)
INSERT INTO cars (make) VALUES (Tesla)
